/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guru.stokcrud.view;

import com.guru.stokcrud.controller.StokKartiController;
import com.guru.stokcrud.gui.IHomePage;
import java.awt.event.ActionListener;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.JTable;

/**
 *
 * @author User
 */
public class HomePage extends javax.swing.JFrame implements IHomePage {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();

        setLocationRelativeTo(null);
        StokKartiController skc = new StokKartiController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        txtStokKodu = new javax.swing.JTextField();
        txtStokAdi = new javax.swing.JTextField();
        java.awt.Label lblStokKodu = new java.awt.Label();
        java.awt.Label lblTarih = new java.awt.Label();
        cmbStokTipi = new javax.swing.JComboBox<>();
        java.awt.Label lblStokAdi = new java.awt.Label();
        cmbStokBirimi = new javax.swing.JComboBox<>();
        java.awt.Label lblStokBirimi = new java.awt.Label();
        txtStokBarkodu = new javax.swing.JTextField();
        java.awt.Label lblStokBarkodu = new java.awt.Label();
        java.awt.Label lblKdvTipi = new java.awt.Label();
        cmbKdvTipi = new javax.swing.JComboBox<>();
        textAciklama = new java.awt.TextArea();
        java.awt.Label lblStokTipi1 = new java.awt.Label();
        java.awt.Label lblStokTipi2 = new java.awt.Label();
        lblTarihLocal = new java.awt.Label();
        btnKaydet = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStokKarti = new javax.swing.JTable();
        btnAra = new javax.swing.JButton();
        btnKopyala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblStokKodu.setText("Stok Kodu");

        lblTarih.setText("Tarih : ");

        cmbStokTipi.setMaximumRowCount(2);
        cmbStokTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", " " }));
        cmbStokTipi.setSelectedItem(null);

        lblStokAdi.setText("Stok Adı");

        cmbStokBirimi.setMaximumRowCount(10);
        cmbStokBirimi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mg", "Gram", "Kg", "Ton", "Litre", "Kasa", "Deste" }));
        cmbStokBirimi.setSelectedItem(null);

        lblStokBirimi.setText("Stok Birimi");

        lblStokBarkodu.setText("Stok Barkodu");

        lblKdvTipi.setText("Kdv Tipi");

        cmbKdvTipi.setMaximumRowCount(10);
        cmbKdvTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.1", "2.2", "10.2", " ", " " }));
        cmbKdvTipi.setSelectedItem(null);

        lblStokTipi1.setText("Açıklama");

        lblStokTipi2.setText("Stok Tipi");

        btnKaydet.setText("Yeni Stok Ekle");

        btnSil.setText("Sil");

        btnGuncelle.setText("Güncelle");

        tblStokKarti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Stok Kodu ", "Stok Adı ", "Stok Tipi", "Birimi", "Barkodu", "Kdv Tipi", "Açıklama", " Tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStokKarti.setToolTipText("");
        tblStokKarti.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblStokKarti);

        btnAra.setText("Ara");

        btnKopyala.setText("Kopyala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStokBarkodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtStokBarkodu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)
                        .addComponent(cmbKdvTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKopyala, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(667, 667, 667)
                        .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuncelle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStokKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStokAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStokAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStokKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(lblKdvTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(lblStokTipi2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbStokTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(lblStokBirimi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cmbStokBirimi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStokTipi1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblTarihLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTarihLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblStokTipi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblStokKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(lblStokAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStokTipi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtStokKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbStokTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStokBirimi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbStokBirimi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtStokAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStokBarkodu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStokBarkodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKdvTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKdvTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKopyala, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        txtStokAdi.getAccessibleContext().setAccessibleName("");
        txtStokAdi.getAccessibleContext().setAccessibleDescription("");
        lblTarihLocal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnKopyala;
    private javax.swing.JButton btnSil;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> cmbKdvTipi;
    private javax.swing.JComboBox<String> cmbStokBirimi;
    private javax.swing.JComboBox<String> cmbStokTipi;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lblTarihLocal;
    private javax.swing.JTable tblStokKarti;
    private java.awt.TextArea textAciklama;
    private javax.swing.JTextField txtStokAdi;
    private javax.swing.JTextField txtStokBarkodu;
    private javax.swing.JTextField txtStokKodu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void buttonKaydet(ActionListener actionListener) {
        btnKaydet.addActionListener(actionListener);
    }

    @Override
    public void buttonGuncelle(ActionListener actionListener) {
        btnGuncelle.addActionListener(actionListener);
    }

    @Override
    public void buttonSil(ActionListener actionListener) {
        btnSil.addActionListener(actionListener);
    }

    @Override
    public String getTarih() {
        return lblTarihLocal.getText();
    }

    @Override
    public void setTarih(Timestamp time) {
        if (time != null) {

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

            String formattedDate = dateFormat.format(time);

            lblTarihLocal.setText(formattedDate);
        } else {

            lblTarihLocal.setText("");
        }
    }

    @Override
    public String getStokKodu() {
        return txtStokKodu.getText();
    }

    @Override
    public void setStokKodu(String stokKodu) {
        txtStokKodu.setText(stokKodu);
    }

    @Override
    public String getStokBarkodu() {
        return txtStokBarkodu.getText();
    }

    @Override
    public void setStokBarkodu(String stokBarkodu) {
        txtStokBarkodu.setText(stokBarkodu);
    }

    @Override
    public String getStokAdi() {
        return txtStokAdi.getText();
    }

    @Override
    public void setStokAdi(String stokAdi) {
        txtStokAdi.setText(stokAdi);
    }

    @Override
    public int getStokTipi() {
        Object selectedItem = cmbStokTipi.getSelectedItem();
        if (selectedItem instanceof String) {
            try {

                return Integer.parseInt((String) selectedItem);
            } catch (NumberFormatException e) {

                System.out.println("Geçersiz sayı formatı: " + selectedItem);
                return 0;
            }
        } else {

            return 0;
        }
    }

    @Override
    public void setStokTipi(String stokTipi) {
        cmbStokTipi.setSelectedItem(stokTipi);
    }

    @Override
    public String getStokBirimi() {
        Object selectedItem = cmbStokBirimi.getSelectedItem();
        if (selectedItem instanceof String) {
            return (String) selectedItem;
        } else {

            return null;
        }
    }

    @Override
    public void setStokBirimi(String stokBirimi) {
        cmbStokBirimi.setSelectedItem(stokBirimi);
    }

    @Override
    public Double getKdvTipi() {
        Object selectedItem = cmbKdvTipi.getSelectedItem();
        if (selectedItem instanceof String) {
            try {

                return Double.parseDouble((String) selectedItem);
            } catch (NumberFormatException e) {

                System.out.println("Geçersiz sayı formatı: " + selectedItem);
                return 0.0;
            }
        } else {

            return 0.0;
        }
    }

    @Override
    public void setKdvTipi(String kdvTipi) {
        cmbKdvTipi.setSelectedItem(kdvTipi);
    }

    @Override
    public String getAciklama() {
        return textAciklama.getText();
    }

    @Override
    public void setAciklama(String aciklama) {
        textAciklama.setText(aciklama);
    }

    @Override
    public JTable getStokTable() {
        return tblStokKarti;
    }

    @Override
    public void showGui() {
        this.setVisible(true);
    }

    @Override
    public void showGuiAfter() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void buttonAra(ActionListener actionListener) {
        btnAra.addActionListener(actionListener);
    }

    @Override
    public void buttonKopyala(ActionListener actionListener) {
        btnKopyala.addActionListener(actionListener);
    }

}
